// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsYuMLwtY7KBmIFw0mHLr3R74IgsjaGoc',
    appId: '1:480424167724:web:41a375f35f27e92fc10489',
    messagingSenderId: '480424167724',
    projectId: 'flutter-iot-security',
    authDomain: 'flutter-iot-security.firebaseapp.com',
    storageBucket: 'flutter-iot-security.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_j30LiYmIQwPTkS86cX2qdz82jICoWI',
    appId: '1:480424167724:android:b8b834aba9fb3099c10489',
    messagingSenderId: '480424167724',
    projectId: 'flutter-iot-security',
    storageBucket: 'flutter-iot-security.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa0IaGBD5rvb-pOuh6qgf1s18TDE4ZH5c',
    appId: '1:480424167724:ios:edb80466c1fbb01dc10489',
    messagingSenderId: '480424167724',
    projectId: 'flutter-iot-security',
    storageBucket: 'flutter-iot-security.firebasestorage.app',
    iosBundleId: 'com.example.flutterIotSecurity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa0IaGBD5rvb-pOuh6qgf1s18TDE4ZH5c',
    appId: '1:480424167724:ios:edb80466c1fbb01dc10489',
    messagingSenderId: '480424167724',
    projectId: 'flutter-iot-security',
    storageBucket: 'flutter-iot-security.firebasestorage.app',
    iosBundleId: 'com.example.flutterIotSecurity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsYuMLwtY7KBmIFw0mHLr3R74IgsjaGoc',
    appId: '1:480424167724:web:f28e13a52c19faffc10489',
    messagingSenderId: '480424167724',
    projectId: 'flutter-iot-security',
    authDomain: 'flutter-iot-security.firebaseapp.com',
    storageBucket: 'flutter-iot-security.firebasestorage.app',
  );
}
